---
services:
  cloud-storage-manager:
    container_name: cloud-storage-manager
    build:
      context: .
      # If you have a custom Dockerfile name, specify:
      # dockerfile: Dockerfile
    ports:
      - "${HOST_PORT:-5001}:5000"
    # (Optional) Mount the current directory if you want live code edits
    # volumes:
    #   - .:/app
